[CI] Refactor cibuild and framework

diff --git a/cibuild/run b/cibuild/run
--- a/cibuild/run
+++ b/cibuild/run
@@ -14,26 +14,53 @@
 # limitations under the License.
 # =============================================================================
 
-if [[ -z "$DOCKER_RUN_ARGS" ]]; then
-  DOCKER_RUN_ARGS=-it
-fi
-
-if [[ -z "$DOCKER_RUN_IMAGE" ]]; then
-  DOCKER_RUN_IMAGE=registry.cn-shanghai.aliyuncs.com/pai-dlc/hybridbackend:developer-nvtf1-py3.6-cu114-ubuntu18.04
+if [[ -z "$REPO" ]]; then
+  REPO=registry.cn-shanghai.aliyuncs.com/pai-dlc/hybridbackend
 fi
 
 nvidia-smi 1>/dev/null 2>/dev/null
 USE_GPU=$?
 
-if [[ $USE_GPU -gt 0 ]]; then
-  DOCKERRUN="docker run"
-else
-  DOCKERRUN="docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all"
-  $DOCKERRUN $DOCKER_RUN_IMAGE echo 1>/dev/null 2>/dev/null
-  DOCKER_USE_NVRT=$?
-  if [[ $DOCKER_USE_NVRT -gt 0 ]]; then
-    DOCKERRUN="nvidia-docker run"
+if [[ ! $USE_GPU -gt 0 ]]; then
+  if [[ -z "$TAG" ]]; then
+    TAG=tf1.15-py3.6-cu114-ubuntu18.04
   fi
+  DOCKERIMAGE=${REPO}:developer-${TAG}
+
+  if [[ -z "$DOCKERRUN" ]]; then
+    DOCKERRUN="sudo docker run -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all"
+    ${DOCKERRUN} ${DOCKERIMAGE} echo 1>/dev/null 2>/dev/null
+    DOCKER_USE_NVRT=$?
+    if [[ $DOCKER_USE_NVRT -gt 0 ]]; then
+      DOCKERRUN="sudo nvidia-docker run -it"
+    fi
+  fi
+else
+  if [[ -z "$TAG" ]]; then
+    TAG=tf1.15-py3.6-manylinux_2_24
+  fi
+  DOCKERIMAGE=${REPO}:developer-${TAG}
+
+  if [[ -z "$DOCKERRUN" ]]; then
+    DOCKERRUN="sudo docker run -it"
+  fi
+fi
+
+if [[ ! -f "cibuild/dockerfiles/Dockerfile.developer-${TAG}" ]]; then
+  echo >&2 "cibuild/dockerfiles/Dockerfile.developer-${TAG} not found"
+  exit 1
+fi
+
+if [[ -z "$DOCKERTAG" ]]; then
+  DOCKERTAG="sudo docker tag"
+fi
+
+if [[ -z "$DOCKERRM" ]]; then
+  DOCKERRM="sudo docker rm"
+fi
+
+if [[ -z "$DOCKERPULL" ]]; then
+  DOCKERPULL="sudo docker pull"
 fi
 
 set -eo pipefail
@@ -41,21 +68,18 @@ set -eo pipefail
 DIR=$(pwd)
 USRPSWD="$(id -u):$(id -g)"
 
-sudo docker tag $DOCKER_RUN_IMAGE ${DOCKER_RUN_IMAGE}-bak || true
-sudo docker rm $DOCKER_RUN_IMAGE || true
-sudo docker pull $DOCKER_RUN_IMAGE
+if [[ -z "$LOCAL" ]]; then
+  $DOCKERTAG ${DOCKERIMAGE} ${DOCKERIMAGE}-bak 1>/dev/null 2>/dev/null || true
+  $DOCKERRM ${DOCKERIMAGE} 1>/dev/null 2>/dev/null || true
+  $DOCKERPULL ${DOCKERIMAGE}
+fi
 
 set -x
 
-sudo ${DOCKERRUN} \
-  ${DOCKER_RUN_ARGS} \
+${DOCKERRUN} \
+  -e PYTHONPATH=$DIR \
   -v $DIR:$DIR \
   -w $DIR \
-  -e PYTHONPATH=$DIR \
-  -e MALLOC_CONF=background_thread:true,metadata_thp:auto \
-  -e NCCL_DEBUG=INFO \
-  -e NCCL_LAUNCH_MODE=PARALLEL \
-  -e TF_GPU_VMEM=false \
   --user ${USRPSWD} \
   --pid=host \
   --ipc=host \
@@ -63,5 +87,5 @@ sudo ${DOCKERRUN} \
   --cap-add=SYS_ADMIN \
   --cap-add=SYS_PTRACE \
   --rm \
-  ${DOCKER_RUN_IMAGE} \
+  ${DOCKERIMAGE} \
   $@
